update pipeline config

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -215,15 +215,29 @@ stages:
                 # Install necessary packages
                 sudo apt-get update && sudo apt-get install -y curl zip default-jre default-jdk
                 
-                # Download JMeter
-                wget "https://apache.mirrors.lucidnetworks.net//jmeter/binaries/apache-jmeter-5.2.1.tgz"
-                tar -xf apache-jmeter-5.2.1.tgz
+                # Set JMeter version and download URL
+                JMETER_VERSION="5.6.2"
+                JMETER_TGZ="apache-jmeter-${JMETER_VERSION}.tgz"
+                
+                # Download and extract JMeter
+                wget "https://archive.apache.org/dist/jmeter/binaries/${JMETER_TGZ}"
+                tar -xf ${JMETER_TGZ}
                 
                 # Unzip performance test files from artifact
-                unzip -o "$(Build.BuildId)-perftests.zip"
+                unzip -o "$(Build.BuildId)-perftests.zip" -d "$(Pipeline.Workspace)/drop-perftests"
                 
+                # Verify that the files are extracted
+                ls -l "$(Pipeline.Workspace)/drop-perftests"
+                echo "Checking for test_data.csv file..."
+                if [ -f "$(Pipeline.Workspace)/drop-perftests/test_data.csv" ]; then
+                  echo "test_data.csv found"
+                else
+                  echo "test_data.csv NOT found"
+                  exit 1
+                fi
+
                 # Set JMeter directory and log paths
-                JMETER_DIR="./apache-jmeter-5.2.1/bin"
+                JMETER_DIR="./apache-jmeter-${JMETER_VERSION}/bin"
                 LOG_DIR="jmeter-logs"
                 
                 # Create directories for logs
