updated pipeline till infra creation

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -35,16 +35,6 @@ stages:
       inputs:
         terraformVersion: '1.6.3'
 
-    # ToDo: Change the workingDirectory path, as applicable to you
-    # Destroy the resources in Azure by running a separate pipeline. 
-    - task: TerraformTaskV3@3
-      displayName: Terraform destroy
-      inputs:
-        provider: 'azurerm'
-        command: 'destroy'
-        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
-        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
-
     # Run Terraform Init on the pipeline agent 
     # ToDo: Replace the resource group name, storage account name, and container name below
     # Run Terraform Init on the pipeline agent 
@@ -59,6 +49,7 @@ stages:
         backendAzureRmStorageAccountName: 'tfstate103417257'
         backendAzureRmContainerName: 'tfstate'
         backendAzureRmKey: "$(access_key)"
+        commandOptions: 
     
     
     # Run Terraform validate on the pipeline agent 
@@ -68,15 +59,23 @@ stages:
         provider: 'azurerm'
         command: 'validate'
 
-    # force unlock with id
-    - task: TerraformTaskV4@4
-      displayName: 'Terraform force unlock'
-      inputs:
-        provider: 'azurerm'
-        command: 'force-unlock'
-        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
-        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
-        commandOptions: '-force-unlock b5843c44-6af9-d123-1637-1b5ef8acdba9'
+    # Check for and unlock the Terraform state if necessary
+    - script: |
+        echo "Checking for Terraform state lock..."
+        LOCK_ID=$(terraform workspace show | grep -oP '(?<=ID: ).*')
+        if [ -n "$LOCK_ID" ]; then
+          echo "State is locked. Attempting to unlock..."
+          for i in {1..5}; do  # Retry up to 5 times
+            terraform force-unlock $LOCK_ID && break || {
+              echo "Failed to unlock state. Retrying in 10 seconds..."
+              sleep 10
+            }
+          done
+        else
+          echo "No lock found."
+        fi
+      displayName: 'Check and Unlock Terraform State'
+      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
 
     # OPTIONAL - This step is needed only if your Terraform VM uses an SSH key pair for login and you want your pipeline agent to connect to it. 
     # Generate an SSH key pair in your local/AZ Cloud shell. Use the public key in the Terraform VM module. 
