updated pipeline

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -160,7 +160,7 @@ stages:
     - task: ArchiveFiles@2
       displayName: 'Archive FakeRestAPI'
       inputs:
-        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/fakerestapi'
+        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
         includeRootFolder: false
         archiveType: 'zip'
         archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
@@ -192,9 +192,9 @@ stages:
   # Deploy FakeRestAPI Web App
   # ToDo: Provide <environment name> you created in your DevOps project
   - deployment: FakeRestAPI
-    pool:
-      vmImage: 'Ubuntu-18.04'      
-    environment: test-vm
+    pool: myAgentPool
+      # vmImage: 'Ubuntu-18.04'      
+    environment: "$(environmentName)"
     strategy:
       runOnce:
         deploy:
@@ -209,22 +209,61 @@ stages:
           #--------------------------------------------#    
           # Run JMeter test suite against the App Service
           - task: CmdLine@2
+            displayName: Run JMeter Test Suite
             inputs:
               script: |
-                wget "https://apache.mirrors.lucidnetworks.net//jmeter/binaries/apache-jmeter-5.2.1.tgz"
-                tar -xf apache-jmeter-5.2.1.tgz
+                # Update package list and install required packages
+                apt-get update
+                apt install -y curl zip default-jre default-jdk
+
+                # Download JMeter from the official Apache mirror
+                JMETER_VERSION="5.2.1"
+                wget "https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz" -O apache-jmeter.tgz
+
+                # Check if the download was successful
+                if [ $? -ne 0 ]; then
+                  echo "JMeter download failed!"
+                  exit 1
+                fi
+
+                # Extract the JMeter archive
+                tar -xf apache-jmeter.tgz
+                JMETER_HOME="./apache-jmeter-${JMETER_VERSION}"
+
+                # Unzip the performance tests package
                 unzip -o $(Build.BuildId)-perftests.zip
-                ./apache-jmeter-5.2.1/bin/jmeter -n -t PerformanceTestSuite.jmx -j jmeter.log -f
-                cat jmeter.log                                                                           # ToDo: Write your commands
-              workingDirectory: $(Pipeline.Workspace)/drop-perftests            # ToDo: Use the artifact name from the task above
-              
+
+                # Run JMeter test suites
+                ${JMETER_HOME}/bin/jmeter -n -t PerformanceTestSuite.jmx -l PerformanceTestSuite.jtl -e -o PerformanceTestSuiteReport
+                ${JMETER_HOME}/bin/jmeter -n -t StressTest.jmx -l StressTest.jtl -e -o StressTestReport
+                ${JMETER_HOME}/bin/jmeter -n -t EnduranceTest.jmx -l EnduranceTest.jtl -e -o EnduranceTestReport
+
+                # Display logs from test runs
+                echo "JMeter Performance test log file"
+                cat PerformanceTestSuite.jtl
+                echo "JMeter Stress test log file"
+                cat StressTest.jtl
+                echo "JMeter Endurance test log file"
+                cat EnduranceTest.jtl
+              workingDirectory: $(Pipeline.Workspace)/drop-perftests
+
+          # Archive the JMeter log files
+          - task: ArchiveFiles@2
+            displayName: Get JMeter Log
+            inputs:
+              rootFolderOrFile: "$(Pipeline.Workspace)/drop-perftests/log/jmeter"
+              includeRootFolder: false
+              archiveType: "zip"
+              archiveFile: "$(Pipeline.Workspace)/drop-perftests/log/jmeter-$(Build.BuildId).zip"
+              verbose: true
+
   #--------------------------------------------#  
   # Selenium | Functional UI Tests
   # ToDo: 
   - deployment: VMDeploy
     displayName: Selenium Tests
     environment:
-      name: 'test-vm'        # ToDo: Change/provide a name
+      name: "$(environmentName)"       # ToDo: Change/provide a name
       resourceType: VirtualMachine
       tags: selenium
     strategy:
@@ -232,6 +271,7 @@ stages:
         deploy:
           steps:
           - download: current
+            name: "Download_Tests"
             artifact: drop-uitests     # ToDo: Change/provide a name
             
           - task: Bash@3
